swagger: "2.0"
info:
  title: Cars Service
  description: HTTP service to lookup car models by body style.
  version: ""
host: localhost:8080
paths:
  /cars:
    get:
      tags:
      - cars
      summary: list cars
      description: |-
        Lists car models by body style.

        Required security scopes:
          * `stream:read`
      operationId: cars#list
      parameters:
      - name: style
        in: query
        description: The car body style.
        required: true
        type: string
        enum:
        - sedan
        - hatchback
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/CarsListResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ListUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ListInvalidScopesResponseBody'
      schemes:
      - http
      - ws
      security:
      - jwt: []
    post:
      tags:
      - cars
      summary: add cars
      description: |-
        Add car models.

        Required security scopes:
          * `stream:write`
      operationId: cars#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CarsAddRequestBody'
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/CarscarResponseBodyCollection'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AddUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/AddInvalidScopesResponseBody'
      schemes:
      - http
      - ws
      security:
      - jwt: []
  /cars/login:
    post:
      tags:
      - cars
      summary: login cars
      description: Creates a valid JWT
      operationId: cars#login
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/LoginUnauthorizedResponseBody'
      schemes:
      - http
      - ws
      security:
      - basic: []
definitions:
  AddInvalidScopesResponseBody:
    title: AddInvalidScopesResponseBody
    type: string
    example: Earum et earum et facere.
  AddUnauthorizedResponseBody:
    title: AddUnauthorizedResponseBody
    type: string
    example: Rerum autem pariatur nihil quam labore sit.
  CarsAddRequestBody:
    title: CarsAddRequestBody
    type: object
    properties:
      car:
        $ref: '#/definitions/carRequestBody'
    example:
      car:
        body_style: Laudantium qui minima voluptatibus in incidunt.
        make: Aspernatur totam.
        model: Vero odio odio id autem.
  CarsListResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.car; view=default'
    type: object
    properties:
      body_style:
        type: string
        description: The car body style
        example: In similique autem placeat ad debitis nobis.
      make:
        type: string
        description: The make of the car
        example: Amet nihil.
      model:
        type: string
        description: The car model
        example: Odit reiciendis aperiam perspiciatis harum et.
    description: ListResponseBody result type (default view)
    example:
      body_style: Asperiores rerum et tempore a ea voluptatibus.
      make: Fuga voluptatibus consequuntur et voluptas.
      model: Tenetur adipisci facere aliquam in nulla.
    required:
    - make
    - model
    - body_style
  CarscarResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.goa.car; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/carResponseBody'
    description: AddResponseBody is the result type for an array of carResponseBody
      (default view)
    example:
    - body_style: Quis velit.
      make: Voluptatem aut.
      model: Nihil modi consequuntur impedit culpa dolor iste.
    - body_style: Quis velit.
      make: Voluptatem aut.
      model: Nihil modi consequuntur impedit culpa dolor iste.
    - body_style: Quis velit.
      make: Voluptatem aut.
      model: Nihil modi consequuntur impedit culpa dolor iste.
  ListInvalidScopesResponseBody:
    title: ListInvalidScopesResponseBody
    type: string
    example: At debitis ut dicta porro.
  ListUnauthorizedResponseBody:
    title: ListUnauthorizedResponseBody
    type: string
    example: Et voluptas quos exercitationem eligendi voluptatibus.
  LoginUnauthorizedResponseBody:
    title: LoginUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: Mollitia asperiores.
  carRequestBody:
    title: carRequestBody
    type: object
    properties:
      body_style:
        type: string
        description: The car body style
        example: Amet magnam.
      make:
        type: string
        description: The make of the car
        example: Quia temporibus exercitationem ipsam harum eos excepturi.
      model:
        type: string
        description: The car model
        example: Occaecati aut eum ut quidem.
    example:
      body_style: Sed deleniti.
      make: Quia error aspernatur consectetur animi eum molestiae.
      model: Officia minus labore aut.
    required:
    - make
    - model
    - body_style
  carResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.car; view=default'
    type: object
    properties:
      body_style:
        type: string
        description: The car body style
        example: Beatae dolorem magni officia earum alias magni.
      make:
        type: string
        description: The make of the car
        example: Necessitatibus et laudantium aliquam animi qui harum.
      model:
        type: string
        description: The car model
        example: Veniam atque.
    description: carResponseBody result type (default view)
    example:
      body_style: Cumque ab natus sunt.
      make: Minima ut magnam reiciendis et repellendus ipsam.
      model: Dolore sapiente.
    required:
    - make
    - model
    - body_style
securityDefinitions:
  basic:
    type: basic
    description: Secures the login endpoint.
  jwt:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".
      **Security Scopes**:
        * `stream:read`: Read-only access
        * `stream:write`: Read and write access
    name: Authorization
    in: header
